### ISSUE TITLE
Crash for double click on purchase

### ISSUE THREAD

**Issue by invizorys** [serso/android-checkout#102]
Hello,
I have crash for double click on purchase item:
`java.lang.IllegalArgumentException: Purchase flow associated with requestCode=51966 already exists
                                                                 at org.solovyev.android.checkout.UiCheckout.createPurchaseFlow(UiCheckout.java:198)
                                                                 at org.solovyev.android.checkout.UiCheckout.createOneShotPurchaseFlow(UiCheckout.java:191)
                                                                 at org.solovyev.android.checkout.UiCheckout.createOneShotPurchaseFlow(UiCheckout.java:144)
                                                                 at org.solovyev.android.checkout.UiCheckout.startPurchaseFlow(UiCheckout.java:216)
                                                                 at org.solovyev.android.checkout.UiCheckout.startPurchaseFlow(UiCheckout.java:229)`

**Comment by serso** [comment]
The library doesn't know anything about the UI and can't protect against double-clicks. You should implement the protection yourself. One way to do it is to disable the "Buy" button as soon as it's clicked and until the response from Checkout is received.
