### ISSUE TITLE
java.lang.NullPointerException in version1.2.0

### ISSUE THREAD

**Issue by petrovichtim** [serso/android-checkout#117]
After update version 1.1.0 to 1.2.0  we got this exception in Fabric.
Code of purchases is not changed
`Fatal Exception: java.lang.NullPointerException
       at org.solovyev.android.checkout.CheckoutInventory$Worker.loadPurchases(SourceFile:99)
       at org.solovyev.android.checkout.CheckoutInventory$Worker.onReady(SourceFile:71)
       at org.solovyev.android.checkout.Checkout$2.onBillingSupported(SourceFile:232)
       at org.solovyev.android.checkout.Checkout$2.onSuccess(SourceFile:242)
       at org.solovyev.android.checkout.MainThreadRequestListener$1.run(SourceFile:55)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by serso** [comment]
Do you have any reproduction steps? How often does this happen?

**Comment by serso** [comment]
Prepared a quick fix, not sure I understand how it happened though. Please try version 1.2.1

**Comment by petrovichtim** [comment]
Now i have 33 crashes for 29 users. After roll back to 1.1.0 and crashes hide.
