### ISSUE TITLE
Proguard - Enum results in NoSuchMethodException: values []

### ISSUE THREAD

**Issue by MFlisar** [serso/android-checkout#138]
When trying to compile my app in release I get following exception:

	java.lang.AssertionError: impossible
		 at java.lang.Enum$1.create(Enum.java:269)
		 at java.lang.Enum$1.create(Enum.java:260)
		 at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
		 at java.lang.Enum.getSharedConstants(Enum.java:286)
		 at java.lang.Class.getEnumConstantsShared(Class.java:2291)
		 at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40)
		 at java.util.EnumMap.getKeyUniverse(EnumMap.java:752)
		 at java.util.EnumMap.<init>(EnumMap.java:137)
		 at org.solovyev.android.checkout.Billing.<clinit>(SourceFile:86)
		 at org.solovyev.android.checkout.Billing.a(SourceFile:224)
		 at com.appindustry.everywherelauncher.app.MainApp.e(SourceFile:93)
		 at com.my.app.application.BaseApp.onCreate(SourceFile:87)
		 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
		 at android.app.ActivityThread.-wrap2(ActivityThread.java)
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
		 at android.os.Handler.dispatchMessage(Handler.java:102)
		 at android.os.Looper.loop(Looper.java:154)
		 at android.app.ActivityThread.main(ActivityThread.java:6077)
		 at java.lang.reflect.Method.invoke(Native Method)
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
	  Caused by: java.lang.NoSuchMethodException: values []
		 at java.lang.Class.getMethod(Class.java:1981)
		 at java.lang.Class.getDeclaredMethod(Class.java:1960)
		 at java.lang.Enum$1.create(Enum.java:265)
		 at java.lang.Enum$1.create(Enum.java:260) 
		 at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
		 at java.lang.Enum.getSharedConstants(Enum.java:286) 
		 at java.lang.Class.getEnumConstantsShared(Class.java:2291) 
		 at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40) 
		 at java.util.EnumMap.getKeyUniverse(EnumMap.java:752) 
		 at java.util.EnumMap.<init>(EnumMap.java:137) 
		 at org.solovyev.android.checkout.Billing.<clinit>(SourceFile:86) 
		 at org.solovyev.android.checkout.Billing.a(SourceFile:224) 
		 at com.appindustry.everywherelauncher.app.MainApp.e(SourceFile:93) 
		 at com.my.app.application.BaseApp.onCreate(SourceFile:87) 
		 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
		 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361) 
		 at android.app.ActivityThread.-wrap2(ActivityThread.java) 
		 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
		 at android.os.Handler.dispatchMessage(Handler.java:102) 
		 at android.os.Looper.loop(Looper.java:154) 
		 at android.app.ActivityThread.main(ActivityThread.java:6077) 
		 at java.lang.reflect.Method.invoke(Native Method) 
		 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
		 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

I'm not 100% sure why this suddenly happens, but clean build + manually deleting all intermediate files did not help... I recently updated support library from 26 to 27, but did not change an billing library version, so this may not be related....

And ideas why this happens suddenly?

For now I solve it by forcing proguard to keep the enums like following:

	-keepclassmembers enum * {
		public static **[] values();
		public static ** valueOf(java.lang.String);
	}

**Comment by serso** [comment]
It seems that some other library (or your project) has very aggressive proguard rules that strips away important information from enums. Rules in this libraries are quite [simple](https://github.com/serso/android-checkout/blob/master/lib/proguard-rules.txt) and shouldn't cause this.

**Comment by gubatron** [comment]
This also worked for our app
```
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
```

The issue manifested itself when we upgraded to the android billing library v 1.1.
The stack trace looked similar:
```
06-13 01:39:38.137 18121 18150 I BTEngine: Caused by: java.lang.NoSuchMethodException: values []
06-13 01:39:38.137 18121 18150 I BTEngine:     at java.lang.Class.getMethod(Class.java:2068)
06-13 01:39:38.137 18121 18150 I BTEngine:     at java.lang.Class.getDeclaredMethod(Class.java:2047)
06-13 01:39:38.137 18121 18150 I BTEngine:     at java.lang.Enum$1.create(Enum.java:268)
06-13 01:39:38.137 18121 18150 I BTEngine:     ... 14 more
```
