### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by gitars** [serso/android-checkout#75]
Stemming from: https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/Billing.java#L1268
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gitars/com.gitars.app.HomeActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.android.server.am.ProcessRecord.uid' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
       at android.app.ActivityThread.access$800(ActivityThread.java:187)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5844)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1109)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
Caused by java.lang.NullPointerException: Attempt to read from field 'int com.android.server.am.ProcessRecord.uid' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.ActivityManagerProxy.bindService(ActivityManagerNative.java:3754)
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1970)
       at android.app.ContextImpl.bindService(ContextImpl.java:1939)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
       at org.solovyev.android.checkout.Billing$DefaultServiceConnector.connect(SourceFile:1268)
       at org.solovyev.android.checkout.Billing.connectOnMainThread(SourceFile:6416)
       at org.solovyev.android.checkout.Billing$4.run(SourceFile:408)
       at org.solovyev.android.checkout.MainThread.execute(SourceFile:57)
       at org.solovyev.android.checkout.Billing.connect(SourceFile:405)
       at org.solovyev.android.checkout.Checkout.org.solovyev.android.checkout.Billing.onCheckoutStarted(SourceFile:1612)
       at com.gitars.app.HomeActivity.org.solovyev.android.checkout.Checkout.start(SourceFile:4150)
       at android.app.Activity.performCreate(Activity.java:6190)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2625)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
       at android.app.ActivityThread.access$800(ActivityThread.java:187)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5844)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1109)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
```

**Comment by serso** [comment]
Any details? Do you have reproduction steps? Does it happen often? Or only on a specific Android version/device?

**Comment by serso** [comment]
I've checked crash reports in one of my apps (Calculator++) and in a half year period I got only 30 crashes with the same stack trace. The interesting part is that they all come from one specific phone model: Meizu M3s. Can you confirm that you get crashes from the same phone model?

**Comment by gitars** [comment]
Yup, the crashes were coming exactly from the same model. Thanks for the fix.
