### ISSUE TITLE
Example App Code, App.get(this) ClassCastException

### ISSUE THREAD

**Issue by robertsimoes** [serso/android-checkout#81]
Copied example app code completely because document code didn't seem to work. Any Help Appreciated !

```
public class App extends Application {
public static App get(Activity activity) {
        return  (App) activity.getApplication();
    }

    private final Billing mBilling = new Billing(this, new Billing.DefaultConfiguration() {
        @Override
        public String getPublicKey() {
            return  //Key      }
    });

    public Billing getBilling() {
        return mBilling;
    }
}
```
```
   onCreate(...) { 
  //...
  final Billing billing = App.get(this).getBilling();
        mCheckout = Checkout.forActivity(this, billing);
        mCheckout.start();
        mCheckout.createPurchaseFlow(new PurchaseListener());
        mInventory = mCheckout.makeInventory();
        mInventory.load(Inventory.Request.create()
                .loadAllPurchases()
                .loadSkus(ProductTypes.IN_APP, "supporter_upgrade"), new InventoryCallback());
}
```

trace:

```java
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pressurelabs.posture/com.pressurelabs.posture.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.pressurelabs.posture.App
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
      at android.app.ActivityThread.-wrap12(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6119)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
   Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.pressurelabs.posture.App
      at com.pressurelabs.posture.App.get(App.java:19
```

**Comment by robertsimoes** [comment]
Change manifest to include name of new application class:

<application android:name=".App">
//..
</application> 

Could be worth adding to front page docs. 

More: 
http://stackoverflow.com/questions/10607392/custom-global-application-class-breaks-with-android-app-application-cannot-be-c
